### PR TITLE
started story

### PR DESCRIPTION
**Pull request by JWoltjen**
Hey Greyson we started the story

### CODE REVIEW

**Comment by GreysonElkins** [comment]
I think it's a great start! I'll merge and get another line going.

**Comment by GreysonElkins** [comment]
actually I don't have write access so I can't merge the request.

**Comment by JWoltjen** [comment]
> actually I don't have write access so I can't merge the request.

let me check the settings. have you accessed your email yet?

**Comment by GreysonElkins** [comment]
I have
let me see if I'm still blocked out

**Pull request merged**
